console.log(document.body);
console.log(document.body.childNodes);
console.log(document.body.childNodes[1]); 
console.log(document.body.childNodes[1].childNodes); 
let cont =document.body.childNodes[1];
console.log(cont.firstChild,cont.lastChild );
console.log(cont.firstElementChild);
console.log(cont.lastElementChild);
// cont.lastElementChild.style.Color = "green";
cont.lastElementChild.style.backgroundColor="red";